import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from '@/components/Sidebar';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Global CRM",
  description: "Generated by create next app",
};

// app/layout.js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-slate-800">
        <Sidebar />
        {/* This "ml-64" (margin-left) pushes the content to the right so the sidebar doesn't cover it */}
        <main className="flex-1 ml-64  min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}